// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_service

import (
	"context"
	"time"

	"github.com/daf32/golang-todoapp/internal/core/auth"
	"github.com/daf32/golang-todoapp/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// CreateEmailConfirmationToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateEmailConfirmationToken(ctx context.Context, userID int, ttl time.Duration) (domain.EmailConfirmationToken, error) {
	ret := _mock.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmailConfirmationToken")
	}

	var r0 domain.EmailConfirmationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) (domain.EmailConfirmationToken, error)); ok {
		return returnFunc(ctx, userID, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) domain.EmailConfirmationToken); ok {
		r0 = returnFunc(ctx, userID, ttl)
	} else {
		r0 = ret.Get(0).(domain.EmailConfirmationToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_CreateEmailConfirmationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmailConfirmationToken'
type MockAuthRepository_CreateEmailConfirmationToken_Call struct {
	*mock.Call
}

// CreateEmailConfirmationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) CreateEmailConfirmationToken(ctx interface{}, userID interface{}, ttl interface{}) *MockAuthRepository_CreateEmailConfirmationToken_Call {
	return &MockAuthRepository_CreateEmailConfirmationToken_Call{Call: _e.mock.On("CreateEmailConfirmationToken", ctx, userID, ttl)}
}

func (_c *MockAuthRepository_CreateEmailConfirmationToken_Call) Run(run func(ctx context.Context, userID int, ttl time.Duration)) *MockAuthRepository_CreateEmailConfirmationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateEmailConfirmationToken_Call) Return(emailConfirmationToken domain.EmailConfirmationToken, err error) *MockAuthRepository_CreateEmailConfirmationToken_Call {
	_c.Call.Return(emailConfirmationToken, err)
	return _c
}

func (_c *MockAuthRepository_CreateEmailConfirmationToken_Call) RunAndReturn(run func(ctx context.Context, userID int, ttl time.Duration) (domain.EmailConfirmationToken, error)) *MockAuthRepository_CreateEmailConfirmationToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateRefreshToken(ctx context.Context, userID int, ttl time.Duration) (core_auth.RefreshToken, error) {
	ret := _mock.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 core_auth.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) (core_auth.RefreshToken, error)); ok {
		return returnFunc(ctx, userID, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, time.Duration) core_auth.RefreshToken); ok {
		r0 = returnFunc(ctx, userID, ttl)
	} else {
		r0 = ret.Get(0).(core_auth.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockAuthRepository_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - ttl time.Duration
func (_e *MockAuthRepository_Expecter) CreateRefreshToken(ctx interface{}, userID interface{}, ttl interface{}) *MockAuthRepository_CreateRefreshToken_Call {
	return &MockAuthRepository_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, userID, ttl)}
}

func (_c *MockAuthRepository_CreateRefreshToken_Call) Run(run func(ctx context.Context, userID int, ttl time.Duration)) *MockAuthRepository_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateRefreshToken_Call) Return(refreshToken core_auth.RefreshToken, err error) *MockAuthRepository_CreateRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepository_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID int, ttl time.Duration) (core_auth.RefreshToken, error)) *MockAuthRepository_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) CreateUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockAuthRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockAuthRepository_CreateUser_Call {
	return &MockAuthRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockAuthRepository_CreateUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) Return(user1 domain.User, err error) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockAuthRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndConsumeEmailConfirmationToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetAndConsumeEmailConfirmationToken(ctx context.Context, token string) (domain.EmailConfirmationToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetAndConsumeEmailConfirmationToken")
	}

	var r0 domain.EmailConfirmationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.EmailConfirmationToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.EmailConfirmationToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(domain.EmailConfirmationToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndConsumeEmailConfirmationToken'
type MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call struct {
	*mock.Call
}

// GetAndConsumeEmailConfirmationToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthRepository_Expecter) GetAndConsumeEmailConfirmationToken(ctx interface{}, token interface{}) *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call {
	return &MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call{Call: _e.mock.On("GetAndConsumeEmailConfirmationToken", ctx, token)}
}

func (_c *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call) Return(emailConfirmationToken domain.EmailConfirmationToken, err error) *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call {
	_c.Call.Return(emailConfirmationToken, err)
	return _c
}

func (_c *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call) RunAndReturn(run func(ctx context.Context, token string) (domain.EmailConfirmationToken, error)) *MockAuthRepository_GetAndConsumeEmailConfirmationToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetRefreshToken(ctx context.Context, tokenString string) (core_auth.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 core_auth.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (core_auth.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) core_auth.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		r0 = ret.Get(0).(core_auth.RefreshToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockAuthRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthRepository_Expecter) GetRefreshToken(ctx interface{}, tokenString interface{}) *MockAuthRepository_GetRefreshToken_Call {
	return &MockAuthRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenString)}
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) Return(refreshToken core_auth.RefreshToken, err error) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockAuthRepository_GetRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (core_auth.RefreshToken, error)) *MockAuthRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) RevokeRefreshToken(ctx context.Context, tokenString string) error {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockAuthRepository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthRepository_Expecter) RevokeRefreshToken(ctx interface{}, tokenString interface{}) *MockAuthRepository_RevokeRefreshToken_Call {
	return &MockAuthRepository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenString)}
}

func (_c *MockAuthRepository_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthRepository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_RevokeRefreshToken_Call) Return(err error) *MockAuthRepository_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string) error) *MockAuthRepository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
