// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core_oauth

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// AuthCodeURL provides a mock function for the type MockProvider
func (_mock *MockProvider) AuthCodeURL(state string, codeVerifier string) string {
	ret := _mock.Called(state, codeVerifier)

	if len(ret) == 0 {
		panic("no return value specified for AuthCodeURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(state, codeVerifier)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_AuthCodeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthCodeURL'
type MockProvider_AuthCodeURL_Call struct {
	*mock.Call
}

// AuthCodeURL is a helper method to define mock.On call
//   - state string
//   - codeVerifier string
func (_e *MockProvider_Expecter) AuthCodeURL(state interface{}, codeVerifier interface{}) *MockProvider_AuthCodeURL_Call {
	return &MockProvider_AuthCodeURL_Call{Call: _e.mock.On("AuthCodeURL", state, codeVerifier)}
}

func (_c *MockProvider_AuthCodeURL_Call) Run(run func(state string, codeVerifier string)) *MockProvider_AuthCodeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_AuthCodeURL_Call) Return(s string) *MockProvider_AuthCodeURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_AuthCodeURL_Call) RunAndReturn(run func(state string, codeVerifier string) string) *MockProvider_AuthCodeURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function for the type MockProvider
func (_mock *MockProvider) Exchange(ctx context.Context, code string, codeVerifier string) (UserInfo, error) {
	ret := _mock.Called(ctx, code, codeVerifier)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (UserInfo, error)); ok {
		return returnFunc(ctx, code, codeVerifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) UserInfo); ok {
		r0 = returnFunc(ctx, code, codeVerifier)
	} else {
		r0 = ret.Get(0).(UserInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, code, codeVerifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockProvider_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - codeVerifier string
func (_e *MockProvider_Expecter) Exchange(ctx interface{}, code interface{}, codeVerifier interface{}) *MockProvider_Exchange_Call {
	return &MockProvider_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code, codeVerifier)}
}

func (_c *MockProvider_Exchange_Call) Run(run func(ctx context.Context, code string, codeVerifier string)) *MockProvider_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_Exchange_Call) Return(userInfo UserInfo, err error) *MockProvider_Exchange_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockProvider_Exchange_Call) RunAndReturn(run func(ctx context.Context, code string, codeVerifier string) (UserInfo, error)) *MockProvider_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProvider
func (_mock *MockProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(s string) *MockProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}
