// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users_service

import (
	"context"
	"time"

	"github.com/daf32/golang-todoapp/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// RevokeAllRefreshTokensForUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) RevokeAllRefreshTokensForUser(ctx context.Context, userID int) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllRefreshTokensForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepository_RevokeAllRefreshTokensForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllRefreshTokensForUser'
type MockAuthRepository_RevokeAllRefreshTokensForUser_Call struct {
	*mock.Call
}

// RevokeAllRefreshTokensForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockAuthRepository_Expecter) RevokeAllRefreshTokensForUser(ctx interface{}, userID interface{}) *MockAuthRepository_RevokeAllRefreshTokensForUser_Call {
	return &MockAuthRepository_RevokeAllRefreshTokensForUser_Call{Call: _e.mock.On("RevokeAllRefreshTokensForUser", ctx, userID)}
}

func (_c *MockAuthRepository_RevokeAllRefreshTokensForUser_Call) Run(run func(ctx context.Context, userID int)) *MockAuthRepository_RevokeAllRefreshTokensForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_RevokeAllRefreshTokensForUser_Call) Return(err error) *MockAuthRepository_RevokeAllRefreshTokensForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepository_RevokeAllRefreshTokensForUser_Call) RunAndReturn(run func(ctx context.Context, userID int) error) *MockAuthRepository_RevokeAllRefreshTokensForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersRepository creates a new instance of MockUsersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersRepository {
	mock := &MockUsersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsersRepository is an autogenerated mock type for the UsersRepository type
type MockUsersRepository struct {
	mock.Mock
}

type MockUsersRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersRepository) EXPECT() *MockUsersRepository_Expecter {
	return &MockUsersRepository_Expecter{mock: &_m.Mock}
}

// ChangeUserPassword provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) ChangeUserPassword(ctx context.Context, user domain.User, newPasswordHash string) error {
	ret := _mock.Called(ctx, user, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUserPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) error); ok {
		r0 = returnFunc(ctx, user, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_ChangeUserPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeUserPassword'
type MockUsersRepository_ChangeUserPassword_Call struct {
	*mock.Call
}

// ChangeUserPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
//   - newPasswordHash string
func (_e *MockUsersRepository_Expecter) ChangeUserPassword(ctx interface{}, user interface{}, newPasswordHash interface{}) *MockUsersRepository_ChangeUserPassword_Call {
	return &MockUsersRepository_ChangeUserPassword_Call{Call: _e.mock.On("ChangeUserPassword", ctx, user, newPasswordHash)}
}

func (_c *MockUsersRepository_ChangeUserPassword_Call) Run(run func(ctx context.Context, user domain.User, newPasswordHash string)) *MockUsersRepository_ChangeUserPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_ChangeUserPassword_Call) Return(err error) *MockUsersRepository_ChangeUserPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_ChangeUserPassword_Call) RunAndReturn(run func(ctx context.Context, user domain.User, newPasswordHash string) error) *MockUsersRepository_ChangeUserPassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUnverifiedUsersOlderThan provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUnverifiedUsersOlderThan(ctx context.Context, cutoff time.Time) (int, error) {
	ret := _mock.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnverifiedUsersOlderThan")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int, error)); ok {
		return returnFunc(ctx, cutoff)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int); ok {
		r0 = returnFunc(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnverifiedUsersOlderThan'
type MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call struct {
	*mock.Call
}

// DeleteUnverifiedUsersOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *MockUsersRepository_Expecter) DeleteUnverifiedUsersOlderThan(ctx interface{}, cutoff interface{}) *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call {
	return &MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call{Call: _e.mock.On("DeleteUnverifiedUsersOlderThan", ctx, cutoff)}
}

func (_c *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call) Run(run func(ctx context.Context, cutoff time.Time)) *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call) Return(n int, err error) *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call) RunAndReturn(run func(ctx context.Context, cutoff time.Time) (int, error)) *MockUsersRepository_DeleteUnverifiedUsersOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) DeleteUser(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsersRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsersRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUsersRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUsersRepository_DeleteUser_Call {
	return &MockUsersRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUsersRepository_DeleteUser_Call) Run(run func(ctx context.Context, id int)) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) Return(err error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsersRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockUsersRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUser(ctx context.Context, id int) (domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsersRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUsersRepository_Expecter) GetUser(ctx interface{}, id interface{}) *MockUsersRepository_GetUser_Call {
	return &MockUsersRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUsersRepository_GetUser_Call) Run(run func(ctx context.Context, id int)) *MockUsersRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) Return(user domain.User, err error) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.User, error)) *MockUsersRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUserByEmail(ctx context.Context, email string) (domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUsersRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsersRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUsersRepository_GetUserByEmail_Call {
	return &MockUsersRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) Return(user domain.User, err error) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsersRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (domain.User, error)) *MockUsersRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) GetUsers(ctx context.Context, limit *int, offset *int, emailVerified *bool) ([]domain.User, error) {
	ret := _mock.Called(ctx, limit, offset, emailVerified)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int, *bool) ([]domain.User, error)); ok {
		return returnFunc(ctx, limit, offset, emailVerified)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int, *bool) []domain.User); ok {
		r0 = returnFunc(ctx, limit, offset, emailVerified)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int, *int, *bool) error); ok {
		r1 = returnFunc(ctx, limit, offset, emailVerified)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockUsersRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit *int
//   - offset *int
//   - emailVerified *bool
func (_e *MockUsersRepository_Expecter) GetUsers(ctx interface{}, limit interface{}, offset interface{}, emailVerified interface{}) *MockUsersRepository_GetUsers_Call {
	return &MockUsersRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, limit, offset, emailVerified)}
}

func (_c *MockUsersRepository_GetUsers_Call) Run(run func(ctx context.Context, limit *int, offset *int, emailVerified *bool)) *MockUsersRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 *bool
		if args[3] != nil {
			arg3 = args[3].(*bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUsersRepository_GetUsers_Call) Return(users []domain.User, err error) *MockUsersRepository_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUsersRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, limit *int, offset *int, emailVerified *bool) ([]domain.User, error)) *MockUsersRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// PatchUser provides a mock function for the type MockUsersRepository
func (_mock *MockUsersRepository) PatchUser(ctx context.Context, id int, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for PatchUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, id, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, domain.User) error); ok {
		r1 = returnFunc(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsersRepository_PatchUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchUser'
type MockUsersRepository_PatchUser_Call struct {
	*mock.Call
}

// PatchUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - user domain.User
func (_e *MockUsersRepository_Expecter) PatchUser(ctx interface{}, id interface{}, user interface{}) *MockUsersRepository_PatchUser_Call {
	return &MockUsersRepository_PatchUser_Call{Call: _e.mock.On("PatchUser", ctx, id, user)}
}

func (_c *MockUsersRepository_PatchUser_Call) Run(run func(ctx context.Context, id int, user domain.User)) *MockUsersRepository_PatchUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 domain.User
		if args[2] != nil {
			arg2 = args[2].(domain.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsersRepository_PatchUser_Call) Return(user1 domain.User, err error) *MockUsersRepository_PatchUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUsersRepository_PatchUser_Call) RunAndReturn(run func(ctx context.Context, id int, user domain.User) (domain.User, error)) *MockUsersRepository_PatchUser_Call {
	_c.Call.Return(run)
	return _c
}
