// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package statistics_service

import (
	"context"
	"time"

	"github.com/daf32/golang-todoapp/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatisticsRepository creates a new instance of MockStatisticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatisticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatisticsRepository {
	mock := &MockStatisticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatisticsRepository is an autogenerated mock type for the StatisticsRepository type
type MockStatisticsRepository struct {
	mock.Mock
}

type MockStatisticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatisticsRepository) EXPECT() *MockStatisticsRepository_Expecter {
	return &MockStatisticsRepository_Expecter{mock: &_m.Mock}
}

// GetTasks provides a mock function for the type MockStatisticsRepository
func (_mock *MockStatisticsRepository) GetTasks(ctx context.Context, userID *int, from *time.Time, to *time.Time) ([]domain.Task, error) {
	ret := _mock.Called(ctx, userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *time.Time, *time.Time) ([]domain.Task, error)); ok {
		return returnFunc(ctx, userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *time.Time, *time.Time) []domain.Task); ok {
		r0 = returnFunc(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatisticsRepository_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockStatisticsRepository_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *int
//   - from *time.Time
//   - to *time.Time
func (_e *MockStatisticsRepository_Expecter) GetTasks(ctx interface{}, userID interface{}, from interface{}, to interface{}) *MockStatisticsRepository_GetTasks_Call {
	return &MockStatisticsRepository_GetTasks_Call{Call: _e.mock.On("GetTasks", ctx, userID, from, to)}
}

func (_c *MockStatisticsRepository_GetTasks_Call) Run(run func(ctx context.Context, userID *int, from *time.Time, to *time.Time)) *MockStatisticsRepository_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStatisticsRepository_GetTasks_Call) Return(tasks []domain.Task, err error) *MockStatisticsRepository_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockStatisticsRepository_GetTasks_Call) RunAndReturn(run func(ctx context.Context, userID *int, from *time.Time, to *time.Time) ([]domain.Task, error)) *MockStatisticsRepository_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}
