// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tasks_service

import (
	"context"

	"github.com/daf32/golang-todoapp/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTasksRepository creates a new instance of MockTasksRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTasksRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTasksRepository {
	mock := &MockTasksRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTasksRepository is an autogenerated mock type for the TasksRepository type
type MockTasksRepository struct {
	mock.Mock
}

type MockTasksRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTasksRepository) EXPECT() *MockTasksRepository_Expecter {
	return &MockTasksRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTasksRepository
func (_mock *MockTasksRepository) CreateTask(ctx context.Context, task domain.Task) (domain.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasksRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTasksRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *MockTasksRepository_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTasksRepository_CreateTask_Call {
	return &MockTasksRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTasksRepository_CreateTask_Call) Run(run func(ctx context.Context, task domain.Task)) *MockTasksRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasksRepository_CreateTask_Call) Return(task1 domain.Task, err error) *MockTasksRepository_CreateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTasksRepository_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task domain.Task) (domain.Task, error)) *MockTasksRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockTasksRepository
func (_mock *MockTasksRepository) DeleteTask(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTasksRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTasksRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTasksRepository_Expecter) DeleteTask(ctx interface{}, id interface{}) *MockTasksRepository_DeleteTask_Call {
	return &MockTasksRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, id)}
}

func (_c *MockTasksRepository_DeleteTask_Call) Run(run func(ctx context.Context, id int)) *MockTasksRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasksRepository_DeleteTask_Call) Return(err error) *MockTasksRepository_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTasksRepository_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, id int) error) *MockTasksRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type MockTasksRepository
func (_mock *MockTasksRepository) GetTask(ctx context.Context, id int) (domain.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (domain.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) domain.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasksRepository_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTasksRepository_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTasksRepository_Expecter) GetTask(ctx interface{}, id interface{}) *MockTasksRepository_GetTask_Call {
	return &MockTasksRepository_GetTask_Call{Call: _e.mock.On("GetTask", ctx, id)}
}

func (_c *MockTasksRepository_GetTask_Call) Run(run func(ctx context.Context, id int)) *MockTasksRepository_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTasksRepository_GetTask_Call) Return(task domain.Task, err error) *MockTasksRepository_GetTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTasksRepository_GetTask_Call) RunAndReturn(run func(ctx context.Context, id int) (domain.Task, error)) *MockTasksRepository_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function for the type MockTasksRepository
func (_mock *MockTasksRepository) GetTasks(ctx context.Context, userID *int, limit *int, offset *int) ([]domain.Task, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int, *int) ([]domain.Task, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int, *int, *int) []domain.Task); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int, *int, *int) error); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasksRepository_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTasksRepository_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *int
//   - limit *int
//   - offset *int
func (_e *MockTasksRepository_Expecter) GetTasks(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockTasksRepository_GetTasks_Call {
	return &MockTasksRepository_GetTasks_Call{Call: _e.mock.On("GetTasks", ctx, userID, limit, offset)}
}

func (_c *MockTasksRepository_GetTasks_Call) Run(run func(ctx context.Context, userID *int, limit *int, offset *int)) *MockTasksRepository_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTasksRepository_GetTasks_Call) Return(tasks []domain.Task, err error) *MockTasksRepository_GetTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTasksRepository_GetTasks_Call) RunAndReturn(run func(ctx context.Context, userID *int, limit *int, offset *int) ([]domain.Task, error)) *MockTasksRepository_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// PatchTask provides a mock function for the type MockTasksRepository
func (_mock *MockTasksRepository) PatchTask(ctx context.Context, id int, task domain.Task) (domain.Task, error) {
	ret := _mock.Called(ctx, id, task)

	if len(ret) == 0 {
		panic("no return value specified for PatchTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, domain.Task) (domain.Task, error)); ok {
		return returnFunc(ctx, id, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, domain.Task) domain.Task); ok {
		r0 = returnFunc(ctx, id, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, domain.Task) error); ok {
		r1 = returnFunc(ctx, id, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTasksRepository_PatchTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchTask'
type MockTasksRepository_PatchTask_Call struct {
	*mock.Call
}

// PatchTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - task domain.Task
func (_e *MockTasksRepository_Expecter) PatchTask(ctx interface{}, id interface{}, task interface{}) *MockTasksRepository_PatchTask_Call {
	return &MockTasksRepository_PatchTask_Call{Call: _e.mock.On("PatchTask", ctx, id, task)}
}

func (_c *MockTasksRepository_PatchTask_Call) Run(run func(ctx context.Context, id int, task domain.Task)) *MockTasksRepository_PatchTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 domain.Task
		if args[2] != nil {
			arg2 = args[2].(domain.Task)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTasksRepository_PatchTask_Call) Return(task1 domain.Task, err error) *MockTasksRepository_PatchTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTasksRepository_PatchTask_Call) RunAndReturn(run func(ctx context.Context, id int, task domain.Task) (domain.Task, error)) *MockTasksRepository_PatchTask_Call {
	_c.Call.Return(run)
	return _c
}
